import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import ParticleLoading from "@/components/ParticleLoading";
import CustomCursor from "@/components/CustomCursor";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
 (function () {
    document.documentElement.dataset.theme = "dark";
    document.documentElement.style.colorScheme = "dark";

    try {
      localStorage.setItem("portfolio-theme", "dark");
    } catch (error) {}
  })();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <head>
        <link
          rel="preload"
          href="/hero/hero-motion-web.mp4"
          as="video"
          type="video/mp4"
        />
      </head>
      <body>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
        />
        <ParticleLoading />
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
